/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#edc065",
        "surface-container-lowest": "#0e0e10",
        "tertiary-container": "#8c6814",
        "tertiary": "#edc065",
        "on-error": "#690005",
        "surface-variant": "#353437",
        "on-surface": "#e4e2e4",
        "on-secondary-container": "#dab36a",
        "on-error-container": "#ffdad6",
        "primary": "#a7c8ff",
        "surface-container-low": "#1b1b1d",
        "inverse-surface": "#e4e2e4",
        "primary-container": "#4a6fa5",
        "on-tertiary": "#412d00",
        "primary-fixed-dim": "#a7c8ff",
        "surface-container": "#1f1f21",
        "on-tertiary-fixed-variant": "#5d4200",
        "surface-bright": "#39393b",
        "on-background": "#e4e2e4",
        "parchment-white": "#EFE6D4",
        "error-container": "#93000a",
        "surface-tint": "#a7c8ff",
        "background-pure": "#000000",
        "tertiary-fixed": "#ffdea4",
        "surface": "#131315",
        "on-primary-container": "#edf1ff",
        "error": "#ffb4ab",
        "outline": "#8d919a",
        "surface-container-highest": "#353437",
        "outline-variant": "#43474f",
        "on-surface-variant": "#c3c6d1",
        "primary-fixed": "#d5e3ff",
        "surface-dim": "#131315",
        "on-primary-fixed-variant": "#1e477b",
        "on-tertiary-container": "#fff0d9",
        "secondary-container": "#604403",
        "surface-stroke": "#2A2A2D",
        "on-primary-fixed": "#001c3b",
        "on-tertiary-fixed": "#261900",
        "denim-light": "#7DA3CA",
        "on-secondary-fixed": "#261900",
        "background": "#131315",
        "inverse-on-surface": "#303032",
        "secondary": "#e9c176",
        "on-secondary": "#412d00",
        "secondary-fixed": "#ffdea5",
        "surface-container-high": "#2a2a2c",
        "on-primary": "#003060",
        "on-secondary-fixed-variant": "#5d4201",
        "secondary-fixed-dim": "#e9c176",
        "inverse-primary": "#395f94"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "container-max": "1440px",
        "stack-xl": "64px",
        "stack-lg": "32px",
        "margin-desktop": "80px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
